version: "3"

services:
  reward-service:
    build: "./reward"
    ports:
      - "1337:80"
  bandit-service:
    build: './bandit'
    ports:
      - "1338:80"
    depends_on:
      - reward-service
